name: Deploy mkdocs

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        # PostgresのDocker imageを使用
        image: plantuml/plantuml-server
        ports:
          - "8080:8080"
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: checkout branch 日本語つかえる？
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: configure git info
        run: |
          git config --global user.name "github-actions-for-deploy"
          git config --global user.email deploy-actions@github.com

      - name: check git status and branch
        run: |
          git status
          git branch

      # mkdocsを利用するためのpython環境のsetupを行う
      - name: setup python env
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          cache: "pip"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: check packages
        run: pip freeze
      #     - name: setup node
      #       uses: actions/setup-node@v4
      #       with:
      #         node-version: "20"
      #         cache: "npm"
      #     - name: install dependencies (node)
      #       run: npm ci

      - name: mkdocs build
        run: |
          mkdocs build --verbose --clean --strict

      #      - name: deploy - 1
      #        run: npx gh-pages -d site
      #      - name: deploy - 2
      #        run: npx gh-pages -d sample -e subdir

      - name: mkdocs deploy - 1
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
      - name: mkdocs deploy - 2
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: sample
          destination_dir: subdir
#      - name: upload contents
#        uses: actions/upload-pages-artifact@v3
#        with:
#          path: site
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    permissions:
#      pages: write
#      id-token: write
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#    steps:
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v4
