name: Deploy mkdocs

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      db:
        # PostgresのDocker imageを使用
        image: plantuml/plantuml-server
        ports:
          - '8080:8080'
    steps:
      - name: checkout branch 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: configure git info
        run: |
          git config --global user.name "github-actions-for-deploy"
          git config --global user.email deploy-actions@github.com

      - name: check git status and branch
        run: |
          git status
          git branch

      # mkdocsを利用するためのpython環境のsetupを行う
      - name: setup python env
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install plantuml-markdown
          pip install mkdocs
          pip install mkdocs_puml
          pip install mkdocs-material
          pip install mkdocs-drawio-exporter
          pip install mkdocs-git-revision-date-plugin
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mdx_truly_sane_lists

      - name: mkdocs build
        run: |
           mkdocs build --verbose --clean --strict

      - name: mkdocs deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
           github_token: ${{ secrets.PERSONAL_TOKEN }}
           publish_dir: site
           
